export const TEXT_INPUT_CHANGE = "TEXT_INPUT_CHANGE"

export const SEND_REGISTER_FORM_REQUEST = "SEND_REGISTER_FORM_REQUEST"
export const SEND_REGISTER_FORM_SUCCESS = "SEND_REGISTER_FORM_SUCCESS"
export const SEND_REGISTER_FORM_FAILURE = "SEND_REGISTER_FORM_FAILURE"