// noun + verb + outcome
// verb + noun + outcome

// Forms
export const UPDATE_TEXT_INPUT = "UPDATE_TEXT_INPUT";

// User Details
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

// User Login
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// User Sessions
export const FETCH_SESSIONS_REQUEST = "FETCH_SESSIONS_REQUEST";
export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
export const FETCH_SESSIONS_FAILURE = "FETCH_SESSIONS_FAILURE";

export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAILURE = "CREATE_SESSION_FAILURE";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAILURE = "UPDATE_SESSION_FAILURE";

export const DELETE_SESSION_REQUEST = "DELETE_SESSION_REQUEST";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_FAILURE = "DELETE_SESSION_FAILURE";

// User Workouts
export const CREATE_WORKOUT_REQUEST = "CREATE_WORKOUT_REQUEST";
export const CREATE_WORKOUT_SUCCESS = "CREATE_WORKOUT_SUCCESS";
export const CREATE_WORKOUT_FAILURE = "CREATE_WORKOUT_FAILURE";

export const UPDATE_WORKOUT_REQUEST = "UPDATE_WORKOUT_REQUEST";
export const UPDATE_WORKOUT_SUCCESS = "UPDATE_WORKOUT_SUCCESS";
export const UPDATE_WORKOUT_FAILURE = "UPDATE_WORKOUT_FAILURE";

export const DELETE_WORKOUT_REQUEST = "DELETE_WORKOUT_REQUEST";
export const DELETE_WORKOUT_FAILURE = "DELETE_WORKOUT_FAILURE";
export const DELETE_WORKOUT_SUCCESS = "DELETE_WORKOUT_SUCCESS";

// Exercise Data
export const LOOKUP_EXERCISES_REQUEST = "LOOKUP_EXERCISES_REQUEST";
export const LOOKUP_EXERCISES_SUCCESS = "LOOKUP_EXERCISES_SUCCESS";
export const LOOKUP_EXERCISES_FAILURE = "LOOKUP_EXERCISES_FAILURE";
