// noun + verb + outcome
// verb + noun + outcome

export const UPDATE_TEXT_INPUT = "UPDATE_TEXT_INPUT"

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const CREATE_SESSION = "CREATE_SESSION"

export const CREATE_WORKOUT = "CREATE_WORKOUT"
// export const CREATE_WORKOUT_SUCCESS = "CREATE_WORKOUT_SUCCESS"
// export const CREATE_WORKOUT_FAILURE = "CREATE_WORKOUT_FAILURE"